name: CI
on:
  push:
  pull_request:

jobs:
  cypress-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - name: Run UI tests
        run: npx cypress run --browser chrome --spec "cypress/e2e/ui/**/*.cy.ts" --config video=true

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-videos
            path: cypress/results/videos/**
            if-no-files-found: ignore

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-screenshots
            path: cypress/results/screenshots/**
            if-no-files-found: ignore

  cypress-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - name: Run API tests
        run: npx cypress run --spec "cypress/e2e/api/**/*.cy.ts"