name: CI
on:
  push:
  pull_request:

jobs:
  cypress-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - name: Run API tests
        run: npx cypress run --spec "cypress/e2e/api/**/*.cy.ts"